# Generated by Django 4.2.13 on 2026-04-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_symbol', models.CharField(default='L', max_length=10)),
                ('currency_name', models.CharField(default='Lempiras', max_length=50)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('tax_name', models.CharField(default='ISV', max_length=20)),
            ],
            options={
                'verbose_name': 'Configuracion del Sistema',
                'verbose_name_plural': 'Configuracion del Sistema',
            },
        ),
    ]
