# Generated by Django 4.2.13 on 2026-04-20 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='invoice_footer',
            field=models.TextField(blank=True, default='Gracias por su compra.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='invoice_header',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='invoice_show_logo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='invoice_show_tax_detail',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='store_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='store_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='store_name',
            field=models.CharField(default='SalesTrack', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='store_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
